/**
 * Generate animal sprites via Scenario "Animated Feature 2.0".
 *
 * Usage:
 *   SCENARIO_API_KEY=... SCENARIO_API_SECRET=... node scripts/gen-sprites.mjs
 *
 * To regenerate specific animals only, edit the ANIMALS array below
 * or filter by id. On success each PNG is written to public/animals/{id}.png
 * and a provenance record is appended to scripts/sprite-sources.json.
 */

import https from 'https';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCES_PATH = resolve(ROOT, 'scripts/sprite-sources.json');

const auth = Buffer.from(
  process.env.SCENARIO_API_KEY + ':' + process.env.SCENARIO_API_SECRET
).toString('base64');

const MODEL = 'model_cox2ghwocuxq1GErcbcXb4aK'; // Animated Feature 2.0
const MODEL_NAME = 'Animated Feature 2.0';

// Add new animals here; existing entries can be regenerated by re-running.
const ANIMALS = [
  {
    id: 'stellerseacow',
    prompt: "Steller's Sea Cow, huge manatee-like prehistoric sea creature, massive dark grey barrel-shaped body, wide flat tail flukes, tiny stubby front flippers, round chubby face, Pixar 3D cartoon style, no clothing no costume no accessories, isolated on dark background, game asset character sprite, full body visible",
    negative: "clothing, costume, jacket, vest, accessories, dolphin, whale, fish, realistic, photo"
  },
  {
    id: 'greatauk',
    prompt: "Great Auk, large extinct flightless seabird, black back white belly, large hooked beak with white spot, short vestigial wings, upright standing posture, looks like a bigger razorbill, Pixar 3D cartoon style, dark background, game asset character sprite, full body",
    negative: "penguin, realistic, photo, clothing, Emperor penguin"
  }
];

// ---- HTTP helper --------------------------------------------------------

function request(opts, body) {
  return new Promise((res, rej) => {
    const chunks = [];
    const req = https.request(opts, r => {
      r.on('data', c => chunks.push(c));
      r.on('end', () => res({ status: r.statusCode, headers: r.headers, body: Buffer.concat(chunks) }));
    });
    req.on('error', rej);
    if (body) req.write(body);
    req.end();
  });
}

// ---- Scenario API -------------------------------------------------------

async function generate(animal) {
  const body = JSON.stringify({
    prompt: animal.prompt,
    negativePrompt: animal.negative,
    negativePromptStrength: 0.8,
    numSamples: 1, guidance: 8, numInferenceSteps: 40,
    width: 512, height: 512, modelId: MODEL
  });
  const r = await request({
    hostname: 'api.cloud.scenario.com', path: '/v1/generate/txt2img', method: 'POST',
    headers: {
      'Authorization': 'Basic ' + auth, 'Accept': 'application/json',
      'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body)
    }
  }, body);
  const j = JSON.parse(r.body);
  // Don't echo the response body — it may reflect auth-related details.
  if (!j.job) throw new Error(`Generate failed HTTP ${r.status}`);
  return j.job.jobId;
}

async function waitJob(jobId) {
  for (let i = 0; i < 30; i++) {
    const r = await request({
      hostname: 'api.cloud.scenario.com', path: '/v1/jobs/' + jobId,
      headers: { 'Authorization': 'Basic ' + auth, 'Accept': 'application/json' }
    });
    const j = JSON.parse(r.body);
    if (j.job.status === 'success') return j.job.metadata?.assetIds?.[0];
    if (j.job.status === 'failed') throw new Error('Job failed');
    process.stdout.write('.');
    await new Promise(r => setTimeout(r, 3000));
  }
  throw new Error('Timeout waiting for job');
}

async function downloadAsset(assetId) {
  // 1. Fetch asset metadata for the signed CDN URL.
  const meta = await request({
    hostname: 'api.cloud.scenario.com', path: '/v1/assets/' + assetId,
    headers: { 'Authorization': 'Basic ' + auth, 'Accept': 'application/json' }
  });
  const url = new URL(JSON.parse(meta.body).asset.url);

  // 2. Download, following up to two redirects (CloudFront sometimes chains).
  let dl = await request({ hostname: url.hostname, path: url.pathname + url.search });
  for (let hops = 0; hops < 2 && (dl.status === 301 || dl.status === 302 || dl.status === 307); hops++) {
    const loc = new URL(dl.headers.location);
    dl = await request({ hostname: loc.hostname, path: loc.pathname + loc.search });
  }
  if (dl.status !== 200) throw new Error(`CDN download failed with status ${dl.status}`);

  // 3. Validate PNG magic bytes before touching disk.
  const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47]);
  if (!dl.body.slice(0, 4).equals(PNG_MAGIC)) {
    throw new Error(
      `Downloaded content is not a PNG (got ${dl.body.slice(0, 4).toString('hex')}). ` +
      `Refusing to overwrite sprite.`
    );
  }

  return dl.body;
}

// ---- Sprite-sources manifest --------------------------------------------

function loadSources() {
  if (!existsSync(SOURCES_PATH)) return {};
  try { return JSON.parse(readFileSync(SOURCES_PATH, 'utf-8')); } catch { return {}; }
}

function saveSources(sources) {
  writeFileSync(SOURCES_PATH, JSON.stringify(sources, null, 2) + '\n');
}

// ---- Main ---------------------------------------------------------------

const sources = loadSources();

for (const animal of ANIMALS) {
  process.stdout.write(`\nGenerating ${animal.id}... `);
  const jobId   = await generate(animal);
  const assetId = await waitJob(jobId);
  const buf     = await downloadAsset(assetId);

  writeFileSync(resolve(ROOT, `public/animals/${animal.id}.png`), buf);
  console.log(` ✓ ${(buf.length / 1024).toFixed(0)} KB`);

  // Record provenance so the style can be reproduced in future batches.
  sources[animal.id] = {
    tool: 'scenario',
    model: MODEL,
    modelName: MODEL_NAME,
    prompt: animal.prompt,
    negative: animal.negative,
    negativePromptStrength: 0.8,
    guidance: 8,
    numInferenceSteps: 40,
    width: 512,
    height: 512,
    generatedAt: new Date().toISOString(),
  };
  saveSources(sources);
}

console.log('\nDone. Provenance written to scripts/sprite-sources.json');
